require "plugins/ground.lua"
require "plugins/jumpwall.lua"
require "plugins/ball.lua"
require "plugins/goomba.lua"
require "plugins/stairs.lua"
require "plugins/massless.lua"
require "plugins/brick.lua"
require "plugins/pipe.lua"
require "plugins/floatground.lua"
require "plugins/coingroup.lua"
require "plugins/movebrick.lua"

--controllers
require "plugins/controllers/empty_controller.lua"
require "plugins/controllers/ground_controller.lua"